### ISSUE TITLE
Siri suggested website

### ISSUE THREAD

**Issue by john422e** [scazan/dogstarorchestra.com#1]
Siri's suggested url is https://dogstarorchestra.com, which redirects to scottcazan.com and also prompts a security warning.
![UNADJUSTEDNONRAW_thumb_2724](https://user-images.githubusercontent.com/23177826/59295906-9e65b180-8c39-11e9-8e7c-e5147a724e9a.jpg)

**Comment by scazan** [comment]
Thanks for this. I'm assuming it is due to the IP address being the same for my personal website. I think this should be solved when I move this over to a different static hosting solution which I'm doing now.

**Comment by john422e** [comment]
Ah, that makes sense. Is DS reimbursing you for hosting? If not we should make that happen.

**Comment by scazan** [comment]
sorry! never responded to this (or possibly responded via email). All is good since server hosting was switched.
